set_location_assignment PIN_E1 -to sys_clk
set_location_assignment PIN_M1 -to sys_rstn
set_location_assignment PIN_D11 -to led[0]
set_location_assignment PIN_C11 -to led[1]
set_location_assignment PIN_E10 -to led[2]
set_location_assignment PIN_F9 -to led[3]
set_location_assignment PIN_E16 -to key[0]
set_location_assignment PIN_E15 -to key[1]
set_location_assignment PIN_M2 -to key[2]
set_location_assignment PIN_M16 -to key[3]
